# Generated by Django 3.2.12 on 2023-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Agent', max_length=200)),
                ('description', models.TextField(default='')),
                ('profile_image', models.ImageField(default='default_profile.jpg', upload_to='agents')),
                ('twitter_link', models.URLField(blank=True, default='')),
                ('facebook_link', models.URLField(blank=True, default='')),
                ('instagram_link', models.URLField(blank=True, default='')),
                ('youtube_link', models.URLField(blank=True, default='')),
            ],
        ),
    ]
