# Generated by Django 3.2.12 on 2023-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='facebook_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='instagram_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='twitter_link',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='youtube_link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
