# Generated by Django 3.2.12 on 2023-06-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='area',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='title',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='listing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.listingtype'),
        ),
    ]
