# Generated by Django 3.2.12 on 2023-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230613_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing_type',
        ),
        migrations.AddField(
            model_name='category',
            name='listing_type',
            field=models.ManyToManyField(blank=True, null=True, to='main.ListingType'),
        ),
    ]
