# Generated by Django 3.2.12 on 2023-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230613_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listing_type',
            field=models.ManyToManyField(blank=True, to='main.ListingType'),
        ),
    ]
