# Generated by Django 3.2.12 on 2023-06-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_listing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='listing_type',
            new_name='listing_types',
        ),
    ]
