# Generated by Django 3.2.12 on 2023-06-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_listing_type_category_listing_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing_types',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.listingtype'),
        ),
    ]
