# Generated by Django 3.2.12 on 2023-06-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='title',
        ),
    ]
