# Generated by Django 3.2.12 on 2023-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230614_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
