# Generated by Django 3.2.12 on 2023-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_category_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
