# Generated by Django 3.2.12 on 2023-06-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_blog_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
    ]
